# docker-compose.yml
services:
  db:
    image: postgres
    container_name: finsight_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finsight
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
